DROP TABLE IF EXISTS SERVICE_MECHANIC CASCADE;
DROP TABLE IF EXISTS MECHANIC CASCADE;
DROP TABLE IF EXISTS SERVICE CASCADE;
DROP TABLE IF EXISTS SERVICE_PART CASCADE;
DROP TABLE IF EXISTS PART CASCADE;
DROP TABLE IF EXISTS CAR_SERVICE_REQUEST CASCADE;
DROP TABLE IF EXISTS CAR_TO_SERVICE CASCADE;
DROP TABLE IF EXISTS INVOICE CASCADE;
DROP TABLE IF EXISTS CAR_TO_BUY CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;
DROP TABLE IF EXISTS SALESMAN CASCADE;
DROP TABLE IF EXISTS ADDRESS CASCADE;















