CREATE TABLE SERVICE_MECHANIC
(
    SERVICE_MECHANIC_ID    SERIAL      NOT NULL,
    HOURS                  INT         NOT NULL,
    COMMENT                VARCHAR(64) NOT NULL,
    CAR_SERVICE_REQUEST_ID INT         NOT NULL,
    MECHANIC_ID            INT         NOT NULL,
    SERVICE_ID             INT         NOT NULL,
    PRIMARY KEY (SERVICE_MECHANIC_ID),
    CONSTRAINT FK_SERVICE_MECHANIC_CAR_SERVICE_REQUEST
        FOREIGN KEY (CAR_SERVICE_REQUEST_ID)
            REFERENCES CAR_SERVICE_REQUEST (CAR_SERVICE_REQUEST_ID),
    CONSTRAINT FK_SERVICE_MECHANIC_MECHANIC
        FOREIGN KEY (MECHANIC_ID)
            REFERENCES MECHANIC (MECHANIC_ID),
    CONSTRAINT FK_SERVICE_MECHANIC_SERVICE
        FOREIGN KEY (SERVICE_ID)
            REFERENCES SERVICE (SERVICE_ID)
);