CREATE TABLE SALESMAN
(
    SALESMAN_ID SERIAL      NOT NULL,
    NAME        VARCHAR(32) NOT NULL,
    SURNAME     VARCHAR(32) NOT NULL,
    PESEL       VARCHAR(32) NOT NULL,
    PRIMARY KEY (SALESMAN_ID),
    UNIQUE (PESEL)
);