CREATE TABLE MECHANIC
(
    MECHANIC_ID SERIAL      NOT NULL,
    NAME        VARCHAR(32) NOT NULL,
    SURNAME     VARCHAR(32) NOT NULL,
    PESEL       VARCHAR(32) NOT NULL,
    PRIMARY KEY (MECHANIC_ID),
    UNIQUE (PESEL)
);