CREATE TABLE ADDRESS
(
    ADDRESS_ID  SERIAL      NOT NULL,
    COUNTRY     VARCHAR(32) NOT NULL,
    CITY        VARCHAR(32) NOT NULL,
    POSTAL_CODE VARCHAR(32) NOT NULL,
    ADDRESS     VARCHAR(64) NOT NULL,
    PRIMARY KEY (ADDRESS_ID)
);