CREATE TABLE CAR_TO_SERVICE
(
    CAR_TO_SERVICE_ID SERIAL      NOT NULL,
    VIN               VARCHAR(20) NOT NULL,
    BRAND             VARCHAR(32) NOT NULL,
    MODEL             VARCHAR(32) NOT NULL,
    YEAR              SMALLINT    NOT NULL,
    PRIMARY KEY (CAR_TO_SERVICE_ID),
    UNIQUE (VIN)
);