CREATE TABLE PART
(
    PART_ID       SERIAL        NOT NULL,
    SERIAL_NUMBER VARCHAR(32)   NOT NULL,
    DESCRIPTION   VARCHAR(64)   NOT NULL,
    PRICE         NUMERIC(7, 2) NOT NULL,
    PRIMARY KEY (PART_ID),
    UNIQUE (SERIAL_NUMBER)
);