CREATE TABLE SERVICE_PART
(
    SERVICE_PART_ID        SERIAL NOT NULL,
    QUANTITY               INT    NOT NULL,
    CAR_SERVICE_REQUEST_ID INT    NOT NULL,
    PART_ID                INT    NOT NULL,
    PRIMARY KEY (SERVICE_PART_ID),
    CONSTRAINT FK_SERVICE_PART_CAR_SERVICE_REQUEST
        FOREIGN KEY (CAR_SERVICE_REQUEST_ID)
            REFERENCES CAR_SERVICE_REQUEST (CAR_SERVICE_REQUEST_ID),
    CONSTRAINT FK_SERVICE_PART_PART
        FOREIGN KEY (PART_ID)
            REFERENCES PART (PART_ID)
);